//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFLEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassingStat
    {
        public int Id { get; set; }
        public System.Guid PassingStatsId { get; set; }
        public System.Guid GameId { get; set; }
        public System.Guid PlayerId { get; set; }
        public int Attempts { get; set; }
        public int Completions { get; set; }
        public int Yards { get; set; }
        public int Touchdowns { get; set; }
        public int Interceptions { get; set; }
        public int TwoPointAttempts { get; set; }
        public int TwoPointMakes { get; set; }
        public string GsisId { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
    }
}
