//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFLCommon
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class DefensiveStat
    {
        public int Id { get; set; }
        public Guid DefensiveStatsId { get; set; }
        public Guid GameId { get; set; }
        public Guid PlayerId { get; set; }
        public string Team { get; set; }
        public int Tackles { get; set; }
        public int Assists { get; set; }
        public int Sacks { get; set; }
        public int Interceptions { get; set; }
        public int ForcedFumbles { get; set; }
        public string GsisId { get; set; }
        [JsonIgnore]
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
        public virtual Team Team1 { get; set; }
    }
}
