//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFLCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.DefensiveStats = new HashSet<DefensiveStat>();
            this.Fumbles = new HashSet<Fumble>();
            this.KickingStats = new HashSet<KickingStat>();
            this.KickReturnStats = new HashSet<KickReturnStat>();
            this.PassingStats = new HashSet<PassingStat>();
            this.PuntingStats = new HashSet<PuntingStat>();
            this.PuntReturnStats = new HashSet<PuntReturnStat>();
            this.ReceivingStats = new HashSet<ReceivingStat>();
            this.RushingStats = new HashSet<RushingStat>();
        }
    
        public int Id { get; set; }
        public System.Guid GameId { get; set; }
        public string HomeTeam { get; set; }
        public string AwayTeam { get; set; }
        public System.DateTime DateTime { get; set; }
        public string SeasonType { get; set; } = "PRE";
        public int Season { get; set; }
        public long Eid { get; set; }
        public long GameKey { get; set; }
        public int Week { get; set; }
        public int HTScoreFirstQtr { get; set; }
        public int HTScoreSecondQtr { get; set; }
        public int HTScoreThirdQtr { get; set; }
        public int HTScoreFourthQtr { get; set; }
        public int HTScoreOT { get; set; }
        public int HTScoreFinal { get; set; }
        public int ATScoreFirstQtr { get; set; }
        public int ATScoreSecondQtr { get; set; }
        public int ATScoreThirdQtr { get; set; }
        public int ATScoreFourthQtr { get; set; }
        public int ATScoreOT { get; set; }
        public int ATScoreFinal { get; set; }
        public bool NeutralField { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefensiveStat> DefensiveStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fumble> Fumbles { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual SeasonType SeasonType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KickingStat> KickingStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KickReturnStat> KickReturnStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PassingStat> PassingStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PuntingStat> PuntingStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PuntReturnStat> PuntReturnStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceivingStat> ReceivingStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RushingStat> RushingStats { get; set; }
    }
}
