//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFLCommon
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class KickReturnStat
    {
        public int Id { get; set; }
        public Guid KickReturnStatsId { get; set; }
        public Guid GameId { get; set; }
        public Guid PlayerId { get; set; }
        public string Team { get; set; }
        public int Returns { get; set; }
        public int Average { get; set; }
        public int Touchdowns { get; set; }
        public int Long { get; set; }
        public int LongTouchdown { get; set; }
        public string GsisId { get; set; }
        [JsonIgnore]
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
        public virtual Team Team1 { get; set; }
    }
}
