//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFLCommon
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class KickingStat
    {
        public int Id { get; set; }
        public Guid KickingStatsId { get; set; }
        public Guid GameId { get; set; }
        public Guid PlayerId { get; set; }
        public string Team { get; set; }
        public int FieldGoalsMade { get; set; }
        public int FieldGoalsAttempted { get; set; }
        public int Yards { get; set; }
        public int TotalPoints { get; set; }
        public int ExtraPointsMade { get; set; }
        public int ExtraPointsMissed { get; set; }
        public int ExtraPointsAttempted { get; set; }
        public int ExtraPointsBlocked { get; set; }
        public int ExtraPointsTotal { get; set; }
        public string GsisId { get; set; }
        [JsonIgnore]
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
        public virtual Team Team1 { get; set; }
    }
}
