//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFLCommon
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.DefensiveStats = new HashSet<DefensiveStat>();
            this.Fumbles = new HashSet<Fumble>();
            this.KickingStats = new HashSet<KickingStat>();
            this.KickReturnStats = new HashSet<KickReturnStat>();
            this.PassingStats = new HashSet<PassingStat>();
            this.PlayersTeamsGames = new HashSet<PlayersTeamsGame>();
            this.PuntingStats = new HashSet<PuntingStat>();
            this.PuntReturnStats = new HashSet<PuntReturnStat>();
            this.ReceivingStats = new HashSet<ReceivingStat>();
            this.RushingStats = new HashSet<RushingStat>();
        }
    
        public int Id { get; set; }
        public Guid PlayerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Position { get; set; }
        public string Team { get; set; }
        public DateTime Birthdate { get; set; }
        public string College { get; set; }
        public string FullName { get; set; }
        public string GsisId { get; set; }
        public string GsisName { get; set; }
        public int Height { get; set; }
        public int Number { get; set; }
        public int ProfileId { get; set; }
        public string ProfileUrl { get; set; }
        public string Status { get; set; }
        public int Weight { get; set; }
        public int YearsPro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<DefensiveStat> DefensiveStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Fumble> Fumbles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<KickingStat> KickingStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<KickReturnStat> KickReturnStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<PassingStat> PassingStats { get; set; }
        [JsonIgnore]
        public virtual Position Position1 { get; set; }
        [JsonIgnore]
        public virtual Team Team1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<PlayersTeamsGame> PlayersTeamsGames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<PuntingStat> PuntingStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<PuntReturnStat> PuntReturnStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<ReceivingStat> ReceivingStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<RushingStat> RushingStats { get; set; }
    }
}
