//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFLCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayersTeamsGame
    {
        public int Id { get; set; }
        public System.Guid PlayerId { get; set; }
        public string Prefix { get; set; }
        public System.Guid GameId { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
        public virtual Team Team { get; set; }
    }
}
