//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFLCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceivingStat
    {
        public int Id { get; set; }
        public Guid ReceivingStatsId { get; set; }
        public Guid GameId { get; set; }
        public Guid PlayerId { get; set; }
        public int Receptions { get; set; }
        public int Yards { get; set; }
        public int Touchdowns { get; set; }
        public int Long { get; set; }
        public int TwoPointAttempts { get; set; }
        public int TwoPointsMade { get; set; }
        public string GsisId { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
    }
}
