CREATE TABLE [dbo].[Score]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[ScoreId] UNIQUEIDENTIFIER NOT NULL,
    [GameId] UNIQUEIDENTIFIER NOT NULL, 
    [PlayerId] UNIQUEIDENTIFIER NOT NULL, 
    [Team] NVARCHAR(10) NOT NULL, 
    [Type] NVARCHAR(5) NOT NULL, 
    [Yards] INT NOT NULL
)
